# Loki Stack configuration for local development
# Minimal configuration to avoid issues

# Disable PodSecurityPolicy (deprecated in newer Kubernetes versions)
podSecurityPolicy:
  enabled: false

# Loki configuration
loki:
  enabled: true
  persistence:
    enabled: false
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

# Promtail configuration
promtail:
  enabled: false

# Grafana (disabled since we have our own)
grafana:
  enabled: false

# Prometheus (disabled since we have our own)
prometheus:
  enabled: false

# Service configuration
service:
  type: ClusterIP
  port: 3100
