# Simple Loki configuration for chart version 2.10.2
# Minimal configuration to avoid PodSecurityPolicy issues

# Disable PodSecurityPolicy (deprecated in newer Kubernetes versions)
rbac:
  pspEnabled: false

# Global PodSecurityPolicy disable (deprecated in newer Kubernetes versions)
podSecurityPolicy:
  enabled: false

# Promtail is now deployed as a separate chart

# Basic Loki configuration
loki:
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

# Promtail already disabled above

# Service configuration
service:
  type: ClusterIP
  port: 3100

# Persistence (disabled for local development)
persistence:
  enabled: false

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
