# Loki configuration for chart version 5.36.0
# Single binary mode for local development

# Disable PodSecurityPolicy (deprecated in newer Kubernetes versions)
podSecurityPolicy:
  enabled: false

# Use single binary mode (simpler for local development)
singleBinary:
  enabled: true
  replicas: 1

# Basic Loki configuration
loki:
  # Storage configuration - use local filesystem for development
  storage:
    type: 'filesystem'
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  
  # Schema configuration
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  
  # Limits configuration (simplified)
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    max_query_parallelism: 32
    max_streams_per_user: 0
    max_line_size: 256000
    max_entries_limit_per_query: 5000
    max_query_series: 500
    max_query_lookback: 0s
    max_query_length: 721h
    cardinality_limit: 100000
    max_streams_matchers_per_query: 1000
    max_concurrent_tail_requests: 10
    per_stream_rate_limit: 3MB
    per_stream_rate_limit_burst: 15MB
    max_global_streams_per_user: 5000
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6

# Service configuration
service:
  type: ClusterIP
  port: 3100

# Persistence (disabled for local development)
persistence:
  enabled: false

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

# Disable Promtail for now (we can add it later if needed)
promtail:
  enabled: false
