# Simple Loki configuration for chart version 6.40.0
# Single binary mode for local development

# Disable PodSecurityPolicy (deprecated in newer Kubernetes versions)
rbac:
  pspEnabled: false

# Global PodSecurityPolicy disable (deprecated in newer Kubernetes versions)
podSecurityPolicy:
  enabled: false

# Deployment mode - single binary for local development
deploymentMode: SingleBinary

# Basic Loki configuration for 6.x
loki:
  # Use test schema for local development (no persistence)
  useTestSchema: true
  
  # Storage configuration for local development
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
      compactor: loki-compactor
      indexGateway: loki-index-gateway
      bloomGateway: loki-bloom-gateway
      bloomCompactor: loki-bloom-compactor
      bloomBuilder: loki-bloom-builder
      bloomPlanner: loki-bloom-planner
      overridesExporter: loki-overrides-exporter
      patternIngester: loki-pattern-ingester
      read: loki-read
      write: loki-write
      backend: loki-backend
      queryFrontend: loki-query-frontend
      queryScheduler: loki-query-scheduler
      querier: loki-querier
      ingester: loki-ingester
      distributor: loki-distributor

# Promtail already disabled above

# Service configuration
service:
  type: ClusterIP
  port: 3100

# Persistence (disabled for local development)
persistence:
  enabled: false

# Resource limits - reduced for local development
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Override cache resource requirements
chunksCache:
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi

resultsCache:
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
