tempo:
  repository: grafana/tempo
  tag: "2.3.1"
  pullPolicy: IfNotPresent

  ## Additional container args
  extraArgs: {}

  ## Container Ports
  containerPorts:
    jaeger-thrift-compact: 6831
    jaeger-thrift-binary: 6832
    jaeger-grpc: 14250
    jaeger-thrift-http: 14268
    zipkin: 9411
    otlp-grpc: 4317
    otlp-http: 4318
    opencensus: 55678

  ## Resource requests and limits
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 32Mi

  ## Storage configuration
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      
  ## Server configuration
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095

  ## Distributor configuration
  distributor:
    receivers:
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      opencensus:
        endpoint: 0.0.0.0:55678

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 3100

# Persistence (disabled for local development)
persistence:
  enabled: false

# ConfigMap for tempo configuration
config: |
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095

  distributor:
    receivers:
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      opencensus:
        endpoint: 0.0.0.0:55678

  ingester:
    lifecycler:
      address: 127.0.0.1
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
      final_sleep: 0s

  memberlist:
    abort_if_cluster_join_fails: false
    bind_port: 7946
    join_members:
      - tempo-memberlist

  querier: {}

  query_frontend: {}

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
