# CRDs are managed separately via traefik-crds chart

deployment:
  replicas: 1

service:
  type: ClusterIP

ports:
  web:
    port: 8080
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
  traefik:
    port: 9000
    expose:
      default: true
    exposedPort: 8081

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true

metrics:
  prometheus:
    enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

# Enable OpenTelemetry tracing
tracing:
  otlp:
    grpc:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      insecure: true
  serviceName: "traefik"
  sampleRate: 1.0

# Global configuration
globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

# Additional arguments
additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--entrypoints.web.address=:8080"
  - "--entrypoints.websecure.address=:8443"
  - "--entrypoints.traefik.address=:9000"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  # TLS configuration for self-signed certificates
  - "--providers.kubernetescrd.allowcrossnamespace=true"
  # OTLP tracing configuration
  - "--tracing.otlp.grpc.endpoint=tempo.monitoring.svc.cluster.local:4317"
  - "--tracing.otlp.grpc.insecure=true"

# Resource limits
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
